default: &default
  adapter: postgresql
  encoding: unicode
  pool: 11
  username: soreasy
  password: tennis
  host: 127.0.0.1
development:
  <<: *default
  database: test_dev
test:
  <<: *default
  database: test_test
